### ISSUE TITLE
Build failed due to HBaseSink API change

### ISSUE THREAD

**Issue by karol-brejna-i** [gearpump/gearpump-java-example#6] opened 2015-11-19 11:05 UTC
Build fails with:
/gearpump-java-example/src/main/java/kafka/HBaseSinkTask.java:[53,25] error: incompatible types: String cannot be converted to UserConfig

(The api changed. The change is not reflected in the docs either: http://www.gearpump.io/releases/0.6.2/dev-connectors.html#use-of-hbasesink)

New constructor is:

```
public HBaseSink(UserConfig userconfig, String tableName, Configuration configuration) {
        this.userconfig = userconfig;
        this.tableName = tableName;
        this.configuration = configuration;
        super();
    }
```

What is the responsibility of userconfig? What should it hold?

**Comment by clockfly** [comment] 2015-11-19 11:08
@karol-brejna-i 

Thanks for reporting this, yes, you catched a issue.

**Comment by clockfly** [comment] 2015-11-19 11:13
This in-compatibility is caused by fix in 
https://github.com/gearpump/gearpump/issues/1458, when try to enable secure HBase.

I will assign this to @huafengw  to fix this API incompatiblity.

**Comment by clockfly** [comment] 2015-11-19 11:13
For temporary, You can use UserConfig.empty() to bypass this.

**Closed as completed** 2016-01-28 06:08 UTC
